#!/bin/bash
(set -o igncr) &>/dev/null && set -o igncr && export SHELLOPTS # ignore cr

unset BASH_ENV # TODO(e-carlin): Necessary?

export HOME_ENV_BASE="$HOME/src/e-carlin/home-env"

_init() {
    local f
    for f in \
        /etc/bashrc \
        /etc/bash.bashrc \
        "$HOME"/src/*/home-env/bashrc.d/*.sh \
        ; do
        if [[ -f $f ]]; then
            source "$f"
        fi
    done
}

_init
unset -f _init