(require 'cl)

(global-set-key  (kbd "C-c ss") 'start-supervisor-server)
(defun start-supervisor-server ()
  (interactive)
  (let ((config (current-window-configuration)))
    (window-configuration-to-register ?f)
    (unwind-protect
    (cl-flet ((shell-name (n)
                       (concat "*shell* " n))
              (create-shell (n)
                            (progn (shell (set-buffer (get-buffer-create n)))
                                   (comint-interrupt-subjob)
                                   (erase-buffer)
                                   (insert (concat "cd ~/src/radiasoft/sirepo" " && " " bash etc/run-" n ".sh local"))
                                   (comint-send-input)
                                   )))
      (let ((server (shell-name "server"))
            (supervisor (shell-name "supervisor"))) ;; TODO(e-carlin): there must be a better way to do this (create-shell supervisor)
        (create-shell supervisor)
        (create-shell server)
        (delete-other-windows)
        (split-window-below 10)
        (select-window (next-window))
        (set-window-buffer nil supervisor)))
    (window-configuration-to-register ?s)
    ;; (set-window-configuration config)
    )
  ))
(provide 'e-radiasoft) ;;; e-radiasoft.el ends here
